// Static PSGC data for the checkout address dropdowns.
//
// The JSON files in data/psgc/ are generated by scripts/build-psgc.mjs (see
// data/psgc/meta.json for the PSGC version). Nothing here calls the PSA API or
// needs the API token, so lookups are instant and independent of PSA's uptime.
//
// Source: Philippine Standard Geographic Code (PSGC), Philippine Statistics
// Authority, CC BY 4.0. Filtered by island group and reduced to code and name.

import provincesJson from "@/data/psgc/provinces.json";
import citiesJson from "@/data/psgc/cities.json";
import barangaysJson from "@/data/psgc/barangays.json";

export type PsgcItem = {
  code: string;
  name: string;
  level: string;
  reg: number;
  prv: number;
  mun: number;
};

// compact form used in barangays.json: [code, name, reg, prv, mun]
type BarangayRow = [string, string, number, number, number];

// numeric: true sorts "Barangay 2" before "Barangay 10"
const byName = (a: PsgcItem, b: PsgcItem) =>
  a.name.localeCompare(b.name, "en", { numeric: true });

function push(map: Map<string, PsgcItem[]>, key: string, item: PsgcItem) {
  const list = map.get(key);
  if (list) list.push(item);
  else map.set(key, [item]);
}

// ---- build lookup tables once, when the module first loads -----------------
const provinces = [...(provincesJson as PsgcItem[])].sort(byName);

const citiesByProv = new Map<string, PsgcItem[]>();
for (const c of citiesJson as PsgcItem[]) push(citiesByProv, `${c.reg}:${c.prv}`, c);

const barangaysByProv = new Map<string, PsgcItem[]>(); // everything under a prv
const barangaysByMun = new Map<string, PsgcItem[]>(); // under one city/municipality
for (const [code, name, reg, prv, mun] of barangaysJson as unknown as BarangayRow[]) {
  const item: PsgcItem = { code, name, level: "Bgy", reg, prv, mun };
  push(barangaysByProv, `${reg}:${prv}`, item);
  push(barangaysByMun, `${reg}:${prv}:${mun}`, item);
}

for (const map of [citiesByProv, barangaysByProv, barangaysByMun]) {
  for (const list of map.values()) list.sort(byName);
}

// ---- public API (same signatures the route handlers already use) -----------

// Provinces plus highly urbanized cities (HUCs, which includes the NCR cities).
// HUCs sit at province level in this dataset (mun = 0, level "City").
export async function getProvinces(): Promise<PsgcItem[]> {
  return provinces;
}

// Cities and municipalities inside one province.
export async function getCities(reg: number, prv: number): Promise<PsgcItem[]> {
  return citiesByProv.get(`${reg}:${prv}`) ?? [];
}

// Barangays of one city/municipality. For a HUC, pass mun = 0: a HUC owns its
// whole prv, so take every barangay in it. That also covers Manila, whose
// barangays sit under its districts (mun 1-16) instead of directly under the city.
export async function getBarangays(reg: number, prv: number, mun: number): Promise<PsgcItem[]> {
  const list =
    mun === 0 ? barangaysByProv.get(`${reg}:${prv}`) : barangaysByMun.get(`${reg}:${prv}:${mun}`);
  return list ?? [];
}